"""Redraw the ML44 learning-rate-schedule figure as a thumbnail asset.

The course figure (ml/11_neural_networks/fig/lr_schedules.pdf, generated by that
chapter's py_src/modern_components_figs.py) labels the dashed blue curve
"linear decay (LMU)". The user flagged that attribution as wrong, so the
thumbnail needs the same figure with the "(LMU)" dropped.

Rather than edit the course repo - which would leave its regenerated figure out
of step with the already-published slide deck - this redraws the figure here.
The curve maths is copied verbatim from `lr_schedule_figure` in that script, so
the shapes are identical to what the lecture showed; only the legend text and
the output format differ.

If the course figure itself gets corrected later, delete this and go back to
    python scripts/pdf_to_asset.py "<ref>/ml/11_neural_networks/fig/lr_schedules.pdf" \
        thumbnails/assets/ml44_lr_schedules.png --dpi 600

Usage:
  python scripts/non_essential/lr_schedules_asset.py [--out PATH] [--dpi N]
"""
import argparse
import logging
import sys
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if sys.stderr.encoding and sys.stderr.encoding.lower() != "utf-8":
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.StreamHandler(sys.stderr),
        logging.FileHandler(LOG_DIR / "lr_schedules_asset.log", encoding="utf-8"),
    ],
)
log = logging.getLogger(__name__)

# Armenian flag palette, same as the course figure.
RED, BLUE, ORANGE = "#D90012", "#0033A0", "#F2A800"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, default=Path("thumbnails/assets/ml44_lr_schedules.png"))
    p.add_argument("--dpi", type=int, default=600)
    a = p.parse_args()

    # Schedule SHAPES on an illustrative 10k-step run (warmup stretched to 4% so it is
    # visible; the papers' real step counts are quoted on the slide, not drawn).
    total, warm = 10_000, 400
    t = np.arange(1, total + 1)

    constant = np.ones_like(t, dtype=float)
    linear = 1.0 - 0.9 * (t - 1) / (total - 1)
    inv_sqrt = np.minimum(t / warm, np.sqrt(warm / t))                # Vaswani et al. (2017) shape
    progress = np.clip((t - warm) / (total - warm), 0.0, 1.0)
    cosine = np.where(t < warm, t / warm, 0.1 + 0.9 * 0.5 * (1 + np.cos(np.pi * progress)))

    fig, ax = plt.subplots(figsize=(6.2, 2.7))
    ax.axvspan(0, warm, color=ORANGE, alpha=0.15, lw=0)
    ax.text(warm * 1.15, 0.05, "warmup", fontsize=9, color="gray")
    ax.plot(t, constant, color="gray", lw=1.6, ls=":", label="constant")
    ax.plot(t, linear, color=BLUE, lw=2.0, ls="--", label="linear decay")
    ax.plot(t, inv_sqrt, color=ORANGE, lw=2.2, label="warmup + inverse sqrt (Vaswani)")
    ax.plot(t, cosine, color=RED, lw=2.6, label="warmup + cosine to 10% (Llama 2)")
    ax.set_xlabel("training step", fontsize=12)
    ax.set_ylabel("learning rate / peak", fontsize=11)
    ax.set_ylim(0, 1.08)
    ax.set_xlim(0, total)
    ax.tick_params(labelsize=10)
    ax.grid(alpha=0.3)
    ax.legend(frameon=False, fontsize=9, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=2)

    fig.tight_layout()
    a.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(a.out, dpi=a.dpi, bbox_inches="tight", pad_inches=0.02, facecolor="white")
    plt.close(fig)

    from PIL import Image
    w, h = Image.open(a.out).size
    log.info(f"Wrote {a.out} ({w}x{h}px, aspect {w / h:.2f})")


if __name__ == "__main__":
    main()
